/*global define */

/**
 * The main module that defines the public interface for interactives.
 */
define(function (require) {
    'use strict';

    var $ = require('jquery');
    var d3 = require('d3');
    var convert = require('interactives/convert');
    var widgetButton = require('interactives/widget-button');
    var widgetCallout = require('interactives/widget-callouts');

	// widget loading command pattern (instead of case statement)
	function loadWidget(widgetContent) {
		var widgets = {
			'button' : buttonConf,
			'callout' : calloutConf
			//, add other widget config here
	    };
	   
	    if (typeof widgets[widgetContent.wtype] !== 'function') {
	      throw new Error('Invalid widget ' + widgetContent.wtype);
	    }

	    return widgets[widgetContent.wtype](widgetContent);
	}
	
	// button widget config - it seems to make sense to move this into widget-button but that's a refactor
	// for another day
	function buttonConf(widgetContent) {
		// TODO - are we conflicting here if we have multiple buttons??
		var config = {
			"id" : widgetContent.id,
			"text" : widgetContent.text
		};
		widgetButton.init(config, eventManager);
        $('#' + widgetContent.targetid).append(widgetButton.getRootEl());
        // subscribe to the button press
		eventManager.subscribe(widgetButton.pressedEventId, function(){alert('yay');});
	}

	// callout widget config 
	function calloutConf(widgetContent) {
		var config = {
			id: "callme",
			show: "all",
			type: "numbered",
			headers: ["Nuclear Reactor function" ],
			textBits: [
			{cols: [ "In a closed circuit, (green) water is pumped at high pressure to the reactor core."]},
			{cols: [ "Heat is generated by fission in the fuel rods in the reactor core, which heats the circulating water. Thick layers of concrete and steel or lead contain the reactor core’s radioactivity."]},
			{cols: [ "In the steam generator, the energy from the heated water is used to boil water from a separate supply. The resulting steam moves through a pipe to a turbine."]},
			{cols: [ "The steam turns the turbine, which is connected to an electricity generator. Power lines distribute the electricity. A typical reactor produces as much as a coal-fired power plant."]},
			{cols: [ "A third supply of water is used to cool the steam so it condenses into water, which is pumped back to the steam generator."]}
			]
		};
		widgetCallout.init(widgetContent, eventManager);
        widgetCallout.draw(d3.select("#" + widgetContent.targetid));
        // todo - your event manager stuff goes here
		
	}

    //Return the module value.
    return {
    	// test method
        version: '0.0.1, jQuery version is: ' + $.fn.jquery,
        // test method to show requirejs functionality - boilerplate to eventually be removed
        convert: convert,
    	init: function init(content, eventManager) {

			// todo - loop over each nested widget (we don't have nested widgets yet in sample json)

			// load the widgets
			content.targetActivity.master.widgets.forEach(function(widgetContent){
				loadWidget(widgetContent.widget);
			});
		}
    };
});
